[template]
src = "nginx.tmpl"
dest = "/etc/nginx/nginx.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/port",
  "/docroot",
  "/index/file",
  "/health/url",
  "/health/http/status",
  "/health/content",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
